name: Runner setup
run-name: ${{ github.actor }} is trying to make this work ğŸš€
on: [push]
jobs:
  setup:
    timeout-minutes: 3
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - name: Install make
        run: apt-get update && apt-get install -y make

  build:
    needs: [setup]
    timeout-minutes: 3
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - name: Install make
        run: apt-get update && apt-get install -y make

      - name: Build project
        run: |
          ls
  #         make build
  # test:
  #   needs: [build]
  #   timeout-minutes: 2
  #   runs-on: self-hosted
  #   container: ubuntu:latest
  #   steps:
  #     - name: Install make
  #       run: apt-get update && apt-get install -y make

  #     - name: Install Python
  #       run: apt-get update && apt-get install -y python3

  #     - name: test project
  #       run: |
  #         pip install pytest
  #         make test
  #     - run: echo "ğŸ This job's status is ${{ job.status }}."
  # deb-package-stuff:
  #   needs: [build]
  #   timeout-minutes: 2
  #   runs-on: self-hosted
  #   container: ubuntu:latest
  #   steps:
  #     - name: Install make
  #       run: apt-get update && apt-get install -y make

  #     - name: build deb package
  #       run: |
  #         make build-deb
  #     - name: Archive deb package
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: deb-package
  #         path: |
  #           counter-v2.0.0.deb
  #     - run: echo "ğŸ This job's status is ${{ job.status }}."
  # lint-debian-package:
  #   needs: [build]
  #   timeout-minutes: 2
  #   runs-on: self-hosted
  #   container: ubuntu:latest
  #   steps:
  #     - name: Install make
  #       run: sudo apt-get update && apt-get install -y make
  #     - name: lint deb package
  #       run: |
  #         apt-get install lintian
  #         make lint-deb
  #     - run: echo "ğŸ This job's status is ${{ job.status }}."
